---
##检查zabbix-release是否安装，没有的话就下载zabbix repo
- name: check zabbix repo
  shell: rpm -qa | grep zabbix-release
  register: has_zabbix
  ignore_errors: True

- name: get zabbix repo
  shell: rpm -Uvh https://repo.zabbix.com/zabbix/5.0/rhel/7/x86_64/zabbix-release-5.0-1.el7.noarch.rpm
  when: has_zabbix.rc != 0

- name: install zabbix-agent
  yum: name=zabbix-agent

- name: copy zabbix-agent conf
  template: src=zabbix_agentd.conf.j2 dest=/etc/zabbix/zabbix_agentd.conf
  tags:
  - conf
  notify:
  - restart zabbix-agent
- name: start zabbix-agent
  service: name=zabbix-agent  state=started enabled=true
