version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:11.11-alpine
    restart: always
    shm_size: 1gb
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_USER: yourname
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdb
      TZ: Asia/Shanghai
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_net

networks: 
  app_net:
    name: app_net
